import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { agents } from "@/shared/schema";

export async function POST() {
  try {
    const existing = await db.select().from(agents);
    if (existing.length > 0) {
      return NextResponse.json({ message: "Database already seeded", count: existing.length });
    }

    const seedAgents = [
      {
        name: "Sales Pilot",
        slug: "sales-pilot",
        shortDescription: "Autonomous sales optimization for Shopify stores. Upsells, abandoned carts, and conversion strategies on autopilot.",
        fullDescription: `Your always-on sales optimization agent that works around the clock.\n\nSales Pilot analyzes your store's customer behavior and purchase patterns to identify revenue opportunities you're missing. It handles abandoned cart recovery with personalized follow-ups, suggests upsell and cross-sell combinations based on what actually converts, and helps you create discount strategies that drive repeat purchases without eroding margins.\n\nConnect it to your Shopify store and get actionable recommendations — not generic advice, but specific moves tailored to your catalog and customer base.`,
        category: "Sales",
        price: "0",
        priceLabel: "Free",
        imageUrl: "",
        capabilities: ["Abandoned Cart Recovery", "Upsell Strategy", "Conversion Analysis", "Discount Optimization", "Customer Segmentation"],
        tags: ["shopify", "sales", "conversion", "revenue"],
        platforms: ["Shopify", "Shopify Plus"],
        publisherName: "AgentClaw",
        version: "1.0.0",
        rating: "0",
        reviewCount: 0,
        purchases: 0,
        views: 0,
        featured: true,
        systemPrompt: "You are Sales Pilot, an expert AI assistant specialized in Shopify e-commerce sales optimization. You help store owners increase revenue through upselling strategies, cross-selling techniques, abandoned cart recovery, dynamic pricing, A/B testing for product pages, and conversion rate optimization. Give specific, actionable advice with real examples. Ask clarifying questions about their store when needed. Be direct and data-driven.",
      },
      {
        name: "Stock Sense",
        slug: "stock-sense",
        shortDescription: "AI-powered inventory management with demand forecasting and smart reorder alerts.",
        fullDescription: `Never run out of your best sellers or sit on dead stock again.\n\nStock Sense uses demand forecasting to predict what you'll need and when. It monitors your inventory levels across channels, sends reorder alerts with suggested quantities, and identifies products that aren't moving so you can liquidate before they become a problem.\n\nWhether you're managing 50 SKUs or 5,000, Stock Sense gives you the inventory intelligence that used to require a dedicated operations team.`,
        category: "Inventory",
        price: "0",
        priceLabel: "Free",
        imageUrl: "",
        capabilities: ["Demand Forecasting", "Reorder Alerts", "Dead Stock Detection", "Multi-Channel Sync", "Cost Analysis"],
        tags: ["inventory", "stock", "forecasting", "supply-chain"],
        platforms: ["Shopify", "WooCommerce", "BigCommerce"],
        publisherName: "AgentClaw",
        version: "1.0.0",
        rating: "0",
        reviewCount: 0,
        purchases: 0,
        views: 0,
        featured: true,
        systemPrompt: "You are Stock Sense, an expert AI assistant specialized in e-commerce inventory management. You help with demand forecasting, reorder point calculations, dead stock identification, multi-warehouse optimization, seasonal planning, and supplier management. Provide specific formulas, thresholds, and strategies. Always consider cost implications and margin optimization. Ask about their current inventory setup to give tailored advice.",
      },
      {
        name: "Support Agent",
        slug: "support-agent",
        shortDescription: "Handle customer tickets, returns, and inquiries 24/7 with AI-powered responses.",
        fullDescription: `Customer support that never sleeps and never loses its cool.\n\nSupport Agent handles the repetitive tickets that eat up your team's time — order status inquiries, return requests, shipping questions, and product information. It responds instantly with accurate, on-brand answers and knows when to escalate to a human.\n\nIt learns from your store's policies and past interactions to get better over time. Set it up once, and let it handle the volume while your team focuses on the complex cases that actually need a human touch.`,
        category: "Support",
        price: "0",
        priceLabel: "Free",
        imageUrl: "",
        capabilities: ["Ticket Resolution", "Return Processing", "Order Tracking", "FAQ Generation", "Escalation Rules"],
        tags: ["support", "customer-service", "tickets", "returns"],
        platforms: ["Shopify", "WooCommerce", "Magento"],
        publisherName: "AgentClaw",
        version: "1.0.0",
        rating: "0",
        reviewCount: 0,
        purchases: 0,
        views: 0,
        featured: true,
        systemPrompt: "You are Support Agent, an expert AI assistant for e-commerce customer support. You help store owners craft customer responses, design return/refund policies, create FAQ content, set up support workflows, and improve customer satisfaction scores. Provide template responses, escalation criteria, and best practices. Always prioritize customer satisfaction while protecting the business. Be empathetic and solution-oriented.",
      },
      {
        name: "SEO Engine",
        slug: "seo-engine",
        shortDescription: "Optimize product pages, meta tags, and content strategy for organic search traffic.",
        fullDescription: `Rank higher without hiring an SEO agency.\n\nSEO Engine audits your product pages, generates optimized meta titles and descriptions, suggests keywords you should be targeting, and monitors your search performance. It handles the technical SEO that most store owners skip — schema markup, image optimization, internal linking, and page speed recommendations.\n\nStop paying for ads on keywords you could be ranking for organically. SEO Engine shows you exactly what to fix and writes the optimized content for you.`,
        category: "Marketing",
        price: "0",
        priceLabel: "Free",
        imageUrl: "",
        capabilities: ["Meta Optimization", "Keyword Research", "Schema Markup", "Content Strategy", "Competitor Analysis"],
        tags: ["seo", "marketing", "organic-traffic", "keywords"],
        platforms: ["Shopify", "WooCommerce"],
        publisherName: "AgentClaw",
        version: "1.0.0",
        rating: "0",
        reviewCount: 0,
        purchases: 0,
        views: 0,
        featured: false,
        systemPrompt: "You are SEO Engine, an expert in e-commerce SEO optimization. Help users with meta title/description writing, keyword research, schema markup implementation, image alt-text optimization, internal linking strategies, page speed improvement, and competitor SEO analysis. Provide specific, technical SEO advice with examples. Write actual meta tags, suggest keywords with search volume estimates, and create actionable SEO checklists. Be practical and results-focused.",
      },
      {
        name: "Insight",
        slug: "insight",
        shortDescription: "Unified analytics with actionable insights across all your sales channels.",
        fullDescription: `Stop guessing, start knowing.\n\nInsight pulls together data from your store, analytics, and ad platforms into a unified view. It calculates the metrics that actually matter — customer lifetime value, true acquisition costs, product-level profitability, and channel attribution — then tells you what to do about it.\n\nGet daily briefings on what's working, what's not, and where to focus your effort. No more switching between dashboards or building spreadsheets to figure out if you're actually profitable.`,
        category: "Analytics",
        price: "0",
        priceLabel: "Free",
        imageUrl: "",
        capabilities: ["Revenue Attribution", "Cohort Analysis", "LTV Calculation", "Funnel Analysis", "Automated Reports"],
        tags: ["analytics", "data", "metrics", "reporting"],
        platforms: ["Shopify", "WooCommerce", "BigCommerce"],
        publisherName: "AgentClaw",
        version: "1.0.0",
        rating: "0",
        reviewCount: 0,
        purchases: 0,
        views: 0,
        featured: false,
        systemPrompt: "You are Insight, an expert in e-commerce analytics and data interpretation. Help users understand their store metrics, set up KPI tracking, perform cohort analysis, calculate customer lifetime value, analyze conversion funnels, and create reporting frameworks. Provide specific formulas, benchmark comparisons, and actionable insights. Explain analytics concepts in simple terms without jargon.",
      },
      {
        name: "Listing Pro",
        slug: "listing-pro",
        shortDescription: "Generate high-converting product titles, descriptions, and optimized listings at scale.",
        fullDescription: `Product listings that actually sell.\n\nListing Pro writes product titles and descriptions optimized for both search engines and conversions. Feed it your product info and it generates compelling copy that highlights benefits, addresses objections, and includes the right keywords.\n\nPerfect for stores with large catalogs that need consistent, high-quality product content without spending hours writing each listing. Supports bulk generation across Shopify, Amazon, eBay, and Etsy.`,
        category: "Product",
        price: "0",
        priceLabel: "Free",
        imageUrl: "",
        capabilities: ["Content Generation", "Bulk Listings", "SEO Copy", "Multi-Platform", "A/B Testing"],
        tags: ["product", "listing", "copywriting", "catalog"],
        platforms: ["Shopify", "Amazon", "eBay", "Etsy"],
        publisherName: "AgentClaw",
        version: "1.0.0",
        rating: "0",
        reviewCount: 0,
        purchases: 0,
        views: 0,
        featured: false,
        systemPrompt: "You are Listing Pro, an expert in creating high-converting e-commerce product listings. Help users write compelling product titles, descriptions, bullet points, and SEO-optimized content. Provide A/B test suggestions, pricing strategies based on market positioning, and multi-channel listing optimization. Write actual product copy when asked, with attention to keywords and conversion psychology. Be creative but data-informed.",
      },
      {
        name: "Social Reach",
        slug: "social-reach",
        shortDescription: "Automate social media content creation and scheduling across all platforms.",
        fullDescription: `Consistent social media presence without the daily grind.\n\nSocial Reach generates platform-specific content from your product catalog, schedules posts at optimal times, and tracks what's driving traffic back to your store. It creates content that fits each platform — carousel posts for Instagram, short-form for TikTok, professional updates for LinkedIn.\n\nStop spending hours creating social content. Let Social Reach maintain your brand presence while you focus on running your business.`,
        category: "Social Media",
        price: "0",
        priceLabel: "Free",
        imageUrl: "",
        capabilities: ["Content Creation", "Auto-Scheduling", "Hashtag Strategy", "ROI Tracking", "Multi-Platform"],
        tags: ["social-media", "instagram", "tiktok", "content"],
        platforms: ["Shopify", "WooCommerce"],
        publisherName: "AgentClaw",
        version: "1.0.0",
        rating: "0",
        reviewCount: 0,
        purchases: 0,
        views: 0,
        featured: false,
        systemPrompt: "You are Social Reach, an expert in social media marketing for e-commerce brands. Help users create engaging social media content, develop posting schedules, craft hashtag strategies, plan product launch campaigns, and measure social media ROI. Provide platform-specific advice for Instagram, Facebook, Twitter/X, and TikTok. Write actual post captions, suggest content calendars, and advise on paid vs organic strategies.",
      },
      {
        name: "Price Lab",
        slug: "price-lab",
        shortDescription: "Dynamic pricing optimization based on demand, competition, and margin targets.",
        fullDescription: `Price smarter, not cheaper.\n\nPrice Lab monitors competitor pricing, analyzes demand patterns, and recommends price adjustments that maximize revenue without killing your margins. It runs simulations before you make changes so you can see the projected impact.\n\nSet your margin floors, define your pricing rules, and let Price Lab handle the rest. It's the pricing analyst your business needs but can't afford to hire.`,
        category: "Pricing",
        price: "0",
        priceLabel: "Free",
        imageUrl: "",
        capabilities: ["Competitor Monitoring", "Dynamic Pricing", "Margin Protection", "Price Simulation", "Bundle Pricing"],
        tags: ["pricing", "competitive", "margins", "revenue"],
        platforms: ["Shopify", "Shopify Plus", "BigCommerce"],
        publisherName: "AgentClaw",
        version: "1.0.0",
        rating: "0",
        reviewCount: 0,
        purchases: 0,
        views: 0,
        featured: true,
        systemPrompt: "You are Price Lab, an expert in e-commerce pricing strategy and optimization. Help users with competitive pricing analysis, dynamic pricing models, margin optimization, bundle pricing strategies, price elasticity concepts, promotional pricing calendars, and MAP compliance. Provide specific pricing formulas, competitor analysis frameworks, and revenue impact calculations. Be analytical and numbers-focused.",
      },
      {
        name: "Ship Flow",
        slug: "ship-flow",
        shortDescription: "End-to-end fulfillment automation with carrier comparison and delivery tracking.",
        fullDescription: `Fulfillment that runs itself.\n\nShip Flow optimizes your entire shipping operation — from carrier selection and rate comparison to tracking notifications and return processing. It routes orders to the cheapest or fastest option based on your rules, sends proactive updates to customers, and handles the paperwork for international shipments.\n\nReduce shipping costs, cut down on "where's my order" tickets, and give your customers the delivery experience they expect from major retailers.`,
        category: "Fulfillment",
        price: "0",
        priceLabel: "Free",
        imageUrl: "",
        capabilities: ["Carrier Comparison", "Order Routing", "Tracking Updates", "Return Processing", "International Shipping"],
        tags: ["fulfillment", "shipping", "logistics", "tracking"],
        platforms: ["Shopify", "WooCommerce", "BigCommerce"],
        publisherName: "AgentClaw",
        version: "1.0.0",
        rating: "0",
        reviewCount: 0,
        purchases: 0,
        views: 0,
        featured: false,
        systemPrompt: "You are Ship Flow, an expert in e-commerce order fulfillment and logistics. Help users optimize shipping workflows, compare carrier rates, set up automated tracking notifications, handle return logistics, manage international shipping compliance, and reduce fulfillment errors. Provide specific carrier comparisons, shipping cost calculations, and workflow automation suggestions. Be practical and cost-conscious.",
      },
    ];

    await db.insert(agents).values(seedAgents);
    return NextResponse.json({ message: "Database seeded", count: seedAgents.length });
  } catch (err) {
    console.error("Seed error:", err);
    return NextResponse.json({ message: "Seed failed" }, { status: 500 });
  }
}
